// <auto-generated />
namespace BookStore2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addadmin3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addadmin3));
        
        string IMigrationMetadata.Id
        {
            get { return "202009160522110_add admin3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
