// <auto-generated />
namespace BookStore2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changedusermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedusermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202010101721118_changed user model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
